<a href="https://colab.research.google.com/github/JuanZapa7a/AINavalEngineering/blob/main/Prac_05_Data_Curation%2C_Feature_Selection_and_Algorithms_Evaluation_in_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 5: Data Curation, Feature Selection and Algorithms Evaluation in Machine Learning






##Data Curation

Many machine learning algorithms make assumptions about your data. It is often a very good
idea to prepare your data in such way to best expose the structure of the problem to the machine
learning algorithms that you intend to use. In this chapter you will discover how to prepare
your data for machine learning in Python using scikit-learn. After completing this lesson you
will know how to:
1. Rescale data.
2. Standardize data.
3. Normalize data.
4. Binarize data.

### Need For Data Pre-processing
You almost always need to pre-process your data. It is a required step. A difficulty is that
different algorithms make different assumptions about your data and may require different
transforms. Further, when you follow all of the rules and prepare your data, sometimes algorithms
can deliver better results without pre-processing.

Generally, I would recommend creating many different views and transforms of your data,
then exercise a handful of algorithms on each view of your dataset. This will help you to flush
out which data transforms might be better at exposing the structure of your problem in general.

### Data Transforms

In this lesson you will work through 4 different data pre-processing recipes for machine learning.
The Pima Indian diabetes dataset is used in each recipe. Each recipe follows the same structure:

* Load the dataset from a URL.
* Split the dataset into the input and output variables for machine learning.
* Apply a pre-processing transform to the input variables.
* Summarize the data to show the change.

The scikit-learn library provides two standard idioms for transforming data. Each are useful
in different circumstances. The transforms are calculated in such a way that they can be applied
to your training data and any samples of data you may have in the future. The scikit-learn
documentation has some information on how to use various different pre-processing methods:
* Fit and Multiple Transform.
* Combined Fit-And-Transform.

The Fit and Multiple Transform method is the preferred approach. You call the `fit()`
function to prepare the parameters of the transform once on your data. Then later you can use
the `transform()` function on the same data to prepare it for modeling and again on the test or
validation dataset or new data that you may see in the future. The Combined Fit-And-Transform
is a convenience that you can use for one off tasks. This might be useful if you are interested
in plotting or summarizing the transformed data. You can review the `preprocess` API in
[scikit-learn](http://scikit-learn.org/stable/modules/classes.html#module-sklearn.preprocessing) .


---
**Load the file from a url to `content/data_sample`**

---

First of all we will load the file from a url and then save it in `content/data_sample`.

In [ ]:
!wget -O /content/sample_data/Corrosion_Detection_Ships.csv https://raw.githubusercontent.com/JuanZapa7a/AINavalEngineering/main/Datasets/Corrosion_Detection_Ships.csv

--2025-03-28 19:03:39--  https://raw.githubusercontent.com/JuanZapa7a/AINavalEngineering/main/Datasets/Corrosion_Detection_Ships.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23278 (23K) [text/plain]
Saving to: ‘/content/sample_data/Corrosion_Detection_Ships.csv’

/content/sample_dat 100%[===================>]  22.73K  --.-KB/s    in 0.002s  

2025-03-28 19:03:39 (8.98 MB/s) - ‘/content/sample_data/Corrosion_Detection_Ships.csv’ saved [23278/23278]



### Rescale Data

When your data is comprised of attributes with varying scales, many machine learning algorithms
can benefit from rescaling the attributes to all have the same scale. Often this is referred to
as normalization and attributes are often rescaled into the range between 0 and 1. This is
useful for optimization algorithms used in the core of machine learning algorithms like gradient
descent. It is also useful for algorithms that weight inputs like regression and neural networks
and algorithms that use distance measures like k-Nearest Neighbors. You can rescale your data
using scikit-learn using the [`MinMaxScaler` class](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html) .

In [ ]:
# Rescale data (between 0 and 1)
from pandas import read_csv
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler
filename = '/content/sample_data/Corrosion_Detection_Ships.csv'
names = ['Years_since_last_inspection',
              'Water_salinity',
              'Water_pressure',
              'Coating_thickness',
              'Anti_corrosion_concentration',
              'Hull_material_density',
              'Inspection_history',
              'Ship_age',
              'Hull_Condition']
data = read_csv(filename, names=names)
array = data.values
# separate array into input and output components
X = array[:,0:8]
Y = array[:,8]
scaler = MinMaxScaler(feature_range=(0, 1))
rescaledX = scaler.fit_transform(X)
# summarize transformed data
set_printoptions(precision=3)
print(rescaledX[0:5,:])

[[0.353 0.744 0.59  0.354 0.    0.501 0.234 0.483]
 [0.059 0.427 0.541 0.293 0.    0.396 0.117 0.167]
 [0.471 0.92  0.525 0.    0.    0.347 0.254 0.183]
 [0.059 0.447 0.541 0.232 0.111 0.419 0.038 0.   ]
 [0.    0.688 0.328 0.354 0.199 0.642 0.944 0.2  ]]


After rescaling you can see that all of the values are in the range between 0 and 1.

### Standardize Data

Standardization is a useful technique to transform attributes with a Gaussian distribution and
differing means and standard deviations to a standard Gaussian distribution with a mean of
0 and a standard deviation of 1. It is most suitable for techniques that assume a Gaussian
distribution in the input variables and work better with rescaled data, such as linear regression,
logistic regression and linear discriminate analysis. You can standardize data using scikit-learn
with the [`StandardScaler class`](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html) .

### Normalize Data

Normalizing in scikit-learn refers to rescaling each observation (row) to have a length of 1 (called
a unit norm or a vector with the length of 1 in linear algebra). This pre-processing method
can be useful for sparse datasets (lots of zeros) with attributes of varying scales when using
algorithms that weight input values such as neural networks and algorithms that use distance
measures such as k-Nearest Neighbors. You can normalize data in Python with scikit-learn
using the [`Normalizer class`](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.Normalizer.html).

In [ ]:
# Normalize data (length of 1)
from sklearn.preprocessing import Normalizer
from pandas import read_csv
from numpy import set_printoptions
filename = '/content/sample_data/Corrosion_Detection_Ships.csv'
names = ['Years_since_last_inspection',
              'Water_salinity',
              'Water_pressure',
              'Coating_thickness',
              'Anti_corrosion_concentration',
              'Hull_material_density',
              'Inspection_history',
              'Ship_age',
              'Hull_Condition']
data = read_csv(filename, names=names)
array = data.values
# separate array into input and output components
X = array[:,0:8]
Y = array[:,8]
scaler = Normalizer().fit(X)
normalizedX = scaler.transform(X)
# summarize transformed data
set_printoptions(precision=3)
print(normalizedX[0:5,:])

[[0.034 0.828 0.403 0.196 0.    0.188 0.004 0.28 ]
 [0.008 0.716 0.556 0.244 0.    0.224 0.003 0.261]
 [0.04  0.924 0.323 0.    0.    0.118 0.003 0.162]
 [0.007 0.588 0.436 0.152 0.622 0.186 0.001 0.139]
 [0.    0.596 0.174 0.152 0.731 0.188 0.01  0.144]]


The rows are normalized to length 1.

### Binarize Data (Make Binary)

You can transform your data using a binary threshold. All values above the threshold are
marked 1 and all equal to or below are marked as 0. This is called binarizing your data or
thresholding your data. It can be useful when you have probabilities that you want to make crisp
values. It is also useful when feature engineering and you want to add new features that indicate
something meaningful. You can create new binary attributes in Python using scikit-learn with
the [`Binarizer class`](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.Binarizer.html) .

In [ ]:
# binarization
from sklearn.preprocessing import Binarizer
from pandas import read_csv
from numpy import set_printoptions
filename = '/content/sample_data/Corrosion_Detection_Ships.csv'
names = ['Years_since_last_inspection',
              'Water_salinity',
              'Water_pressure',
              'Coating_thickness',
              'Anti_corrosion_concentration',
              'Hull_material_density',
              'Inspection_history',
              'Ship_age',
              'Hull_Condition']
data = read_csv(filename, names=names)
array = data.values
# separate array into input and output components
X = array[:,0:8]
Y = array[:,8]
binarizer = Binarizer(threshold=0.0).fit(X)
binaryX = binarizer.transform(X)
# summarize transformed data
set_printoptions(precision=3)
print(binaryX[0:5,:])

[[1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]]


You can see that all values equal or less than 0 are marked 0 and all of those above 0 are
marked 1.

## Feature Selection

The data features that you use to train your machine learning models have a huge influence on
the performance you can achieve. Irrelevant or partially relevant features can negatively impact
model performance. In this chapter you will discover automatic feature selection techniques
that you can use to prepare your machine learning data in Python with scikit-learn. After
completing this lesson you will know how to use:
1. Univariate Selection.
2. Recursive Feature Elimination.
3. Principle Component Analysis.
4. Feature Importance.

Feature selection is a process where you automatically select those features in your data that
contribute most to the prediction variable or output in which you are interested. Having
irrelevant features in your data can decrease the accuracy of many models, especially linear
algorithms like linear and logistic regression. Three benefits of performing feature selection
before modeling your data are:
* **Reduces Overfitting**: Less redundant data means less opportunity to make decisions
based on noise.
* **Improves Accuracy**: Less misleading data means modeling accuracy improves.
* **Reduces Training Time**: Less data means that algorithms train faster.

You can learn more about feature selection with scikit-learn in the article [Feature selection](http://scikit-learn.org/stable/modules/feature_selection.html) .
Each feature selection recipes will use the Hull Corrosion dataset.

### Univariate Selection

Statistical tests can be used to select those features that have the strongest relationship with
the output variable. The scikit-learn library provides the [`SelectKBest class`](http://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectKBest.html#sklearn.feature_selection.SelectKBest) that can be used
with a suite of different statistical tests to select a specific number of features. The example
below uses the chi-squared ($\chi^2$ ) statistical test for non-negative features to select 4 of the best
features from the Hull Corrosion dataset.

In [ ]:
# Feature Extraction with Univariate Statistical Tests (Chi-squared for classification)
from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
# load data
filename = '/content/sample_data/Corrosion_Detection_Ships.csv'
names = ['Years_since_last_inspection',
              'Water_salinity',
              'Water_pressure',
              'Coating_thickness',
              'Anti_corrosion_concentration',
              'Hull_material_density',
              'Inspection_history',
              'Ship_age',
              'Hull_Condition']
data = read_csv(filename, names=names)
X = array[:,0:8]
Y = array[:,8]
# feature extraction
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, Y)
# summarize scores
set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:5,:])

[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]
[[148.    0.   33.6  50. ]
 [ 85.    0.   26.6  31. ]
 [183.    0.   23.3  32. ]
 [ 89.   94.   28.1  21. ]
 [137.  168.   43.1  33. ]]


You can see the scores for each attribute and the 4 attributes chosen (those with the highest
scores): `Water_salinity, Anti_corrosion_concentration, Hull_material_density and Ship_age`. I got the names for the chosen attributes by manually
mapping the index of the 4 highest scores to the index of the attribute names.

### Recursive Feature Elimination

The Recursive Feature Elimination (or RFE) works by recursively removing attributes and
building a model on those attributes that remain. It uses the model accuracy to identify which attributes (and combination of attributes) contribute the most to predicting the target attribute.
You can learn more about the [RFE class](http://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html#sklearn.feature_selection.RFE) in the scikit-learn documentation. The example below
uses RFE with the logistic regression algorithm to select the top 3 features. The choice of
algorithm does not matter too much as long as it is skillful and consistent.

In [ ]:
# Feature Extraction with RFE
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
# load data
filename = '/content/sample_data/Corrosion_Detection_Ships.csv'
names = ['Years_since_last_inspection',
              'Water_salinity',
              'Water_pressure',
              'Coating_thickness',
              'Anti_corrosion_concentration',
              'Hull_material_density',
              'Inspection_history',
              'Ship_age',
              'Hull_Condition']
data = read_csv(filename, names=names)
array = data.values
X = array[:,0:8]
Y = array[:,8]
# feature extraction
model = LogisticRegression(max_iter=500)
rfe = RFE(estimator=model, n_features_to_select=3)
fit = rfe.fit(X, Y)
print("Num Features: {0}".format(fit.n_features_))
print("Selected Features: {0}".format(fit.support_))
print("Feature Ranking: {0}".format(fit.ranking_))

Num Features: 3
Selected Features: [ True False False False False  True  True False]
Feature Ranking: [1 2 4 6 5 1 1 3]


You can see that RFE chose the top 3 features as `Years_since_last_inspection, Hull_material_density and Inspection_history`. These are marked
True in the support array and marked with a choice 1 in the ranking array. Again, you can
manually map the feature indexes to the indexes of attribute names.

### Principal Component Analysis

Principal Component Analysis (or PCA) uses linear algebra to transform the dataset into a
compressed form. Generally this is called a data reduction technique. A property of PCA is that
you can choose the number of dimensions or principal components in the transformed result. In
the example below, we use PCA and select 3 principal components. Learn more about the PCA
class in scikit-learn by reviewing the [API](http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html) .

In [ ]:
# Feature Extraction with PCA
from pandas import read_csv
from sklearn.decomposition import PCA
# load data
filename = '/content/sample_data/Corrosion_Detection_Ships.csv'
names = ['Years_since_last_inspection',
              'Water_salinity',
              'Water_pressure',
              'Coating_thickness',
              'Anti_corrosion_concentration',
              'Hull_material_density',
              'Inspection_history',
              'Ship_age',
              'Hull_Condition']
data = read_csv(filename, names=names)
array = data.values
X = array[:,0:8]
Y = array[:,8]
# feature extraction
pca = PCA(n_components=3)
fit = pca.fit(X)
# summarize components
# The .format() method is used here to insert the values into the string
print("Explained Variance: {}".format(fit.explained_variance_ratio_))
print(fit.components_)

Explained Variance: [0.889 0.062 0.026]
[[-2.022e-03  9.781e-02  1.609e-02  6.076e-02  9.931e-01  1.401e-02
   5.372e-04 -3.565e-03]
 [ 2.265e-02  9.722e-01  1.419e-01 -5.786e-02 -9.463e-02  4.697e-02
   8.168e-04  1.402e-01]
 [ 2.246e-02 -1.434e-01  9.225e-01  3.070e-01 -2.098e-02  1.324e-01
   6.400e-04  1.255e-01]]


You can see that the transformed dataset (3 principal components) bare little resemblance
to the source data.

### Feature Importance

Bagged decision trees like Random Forest and Extra Trees can be used to estimate the importance
of features. In the example below we construct a ExtraTreesClassifier classifier for the Pima
Indians onset of diabetes dataset. You can learn more about the [ExtraTreesClassifier class](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.ExtraTreesClassifier.html)
in the scikit-learn API.

In [ ]:
# Feature Importance with Extra Trees Classifier
from pandas import read_csv
from sklearn.ensemble import ExtraTreesClassifier
# load data
filename = '/content/sample_data/Corrosion_Detection_Ships.csv'
names = ['Years_since_last_inspection',
              'Water_salinity',
              'Water_pressure',
              'Coating_thickness',
              'Anti_corrosion_concentration',
              'Hull_material_density',
              'Inspection_history',
              'Ship_age',
              'Hull_Condition']
data = read_csv(filename, names=names)
array = data.values
X = array[:,0:8]
Y = array[:,8]
# feature extraction
model = ExtraTreesClassifier()
model.fit(X, Y)
print(model.feature_importances_)

[0.111 0.23  0.099 0.08  0.074 0.142 0.12  0.144]


You can see that we are given an importance score for each attribute where the larger the
score, the more important the attribute. The scores suggest at the importance of `Water_salinity, Ship_age and Hull_material_density`.

## Evaluate Machine Learning Algorithms

You need to know how well your algorithms perform on unseen data. The best way to evaluate
the performance of an algorithm would be to make predictions for new data to which you
already know the answers. The second best way is to use clever techniques from statistics called
resampling methods that allow you to make accurate estimates for how well your algorithm will
perform on new data. In this chapter you will discover how you can estimate the accuracy of
your machine learning algorithms using resampling methods in Python and scikit-learn on the
Pima Indians dataset.

Why can’t you train your machine learning algorithm on your dataset and use predictions from
this same dataset to evaluate machine learning algorithms? The simple answer is overfitting.

Imagine an algorithm that remembers every observation it is shown during training. If you
evaluated your machine learning algorithm on the same dataset used to train the algorithm, then
an algorithm like this would have a perfect score on the training dataset. But the predictions it
made on new data would be terrible. We must evaluate our machine learning algorithms on
data that is not used to train the algorithm.

The evaluation is an estimate that we can use to talk about how well we think the algorithm
may actually do in practice. It is not a guarantee of performance. Once we estimate the
performance of our algorithm, we can then re-train the final algorithm on the entire training
dataset and get it ready for operational use. Next up we are going to look at four different
techniques that we can use to split up our training dataset and create useful estimates of
performance for our machine learning algorithms:
* Train and Test Sets.
* k-fold Cross Validation.
* Leave One Out Cross Validation.
* Repeated Random Test-Train Splits.

### Split into Train and Test Sets

The simplest method that we can use to evaluate the performance of a machine learning
algorithm is to use different training and testing datasets. We can take our original dataset and
split it into two parts. Train the algorithm on the first part, make predictions on the second
part and evaluate the predictions against the expected results. The size of the split can depend
on the size and specifics of your dataset, although it is common to use 67% of the data for
training and the remaining 33% for testing.

This algorithm evaluation technique is very fast. It is ideal for large datasets (millions of
records) where there is strong evidence that both splits of the data are representative of the
underlying problem. Because of the speed, it is useful to use this approach when the algorithm
you are investigating is slow to train. A downside of this technique is that it can have a high
variance. This means that differences in the training and test dataset can result in meaningful
differences in the estimate of accuracy. In the example below we split the Pima Indians dataset
into 67%/33% splits for training and test and evaluate the accuracy of a Logistic Regression
model.

In [ ]:
# Evaluate using a train and a test set
from pandas import read_csv
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
# load data
filename = '/content/sample_data/Corrosion_Detection_Ships.csv'
names = ['Years_since_last_inspection',
              'Water_salinity',
              'Water_pressure',
              'Coating_thickness',
              'Anti_corrosion_concentration',
              'Hull_material_density',
              'Inspection_history',
              'Ship_age',
              'Hull_Condition']
data = read_csv(filename, names=names)
array = data.values
X = array[:,0:8]
Y = array[:,8]
test_size = 0.33
seed = 7
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=test_size,
random_state=seed)
model = LogisticRegression(max_iter=500)
model.fit(X_train, Y_train)
result = model.score(X_test, Y_test)
print("Accuracy: %.3f%%" % (result*100.0)) # Corrected line: Applying the string formatting to the string itself.

Accuracy: 78.740%


We can see that the estimated accuracy for the model was approximately 78%. Note that
in addition to specifying the size of the split, we also specify the random seed. Because the
split of the data is random, we want to ensure that the results are reproducible. By specifying
the random seed we ensure that we get the same random numbers each time we run the code
and in turn the same split of data. This is important if we want to compare this result to
the estimated accuracy of another machine learning algorithm or the same algorithm with a
different configuration. To ensure the comparison was apples-for-apples, we must ensure that
they are trained and tested on exactly the same data.

### K-fold Cross Validation

Cross validation is an approach that you can use to estimate the performance of a machine
learning algorithm with less variance than a single train-test set split. It works by splitting
the dataset into $k$-parts (e.g. $k = 5$ or $k = 10$). Each split of the data is called a fold. The
algorithm is trained on $k$ − 1 folds with one held back and tested on the held back fold. This is
repeated so that each fold of the dataset is given a chance to be the held back test set. After
running cross validation you end up with k different performance scores that you can summarize
using a mean and a standard deviation.

The result is a more reliable estimate of the performance of the algorithm on new data. It is
more accurate because the algorithm is trained and evaluated multiple times on different data.
The choice of k must allow the size of each test partition to be large enough to be a reasonable
sample of the problem, whilst allowing enough repetitions of the train-test evaluation of the
algorithm to provide a fair estimate of the algorithms performance on unseen data. For modest
sized datasets in the thousands or tens of thousands of records, k values of 3, 5 and 10 are
common. In the example below we use 10-fold cross validation.

In [ ]:
# Evaluate using Cross Validation
from pandas import read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
# load data
filename = '/content/sample_data/Corrosion_Detection_Ships.csv'
names = ['Years_since_last_inspection',
              'Water_salinity',
              'Water_pressure',
              'Coating_thickness',
              'Anti_corrosion_concentration',
              'Hull_material_density',
              'Inspection_history',
              'Ship_age',
              'Hull_Condition']
data = read_csv(filename, names=names)
array = data.values
X = array[:,0:8]
Y = array[:,8]
num_folds = 10
seed = 7
# Set shuffle=True to enable shuffling
kfold = KFold(n_splits=num_folds, random_state=seed, shuffle=True)
model = LogisticRegression(max_iter=500)
results = cross_val_score(model, X, Y, cv=kfold)
print("Accuracy: %.3f%% (%.3f%%)" % (results.mean()*100.0, results.std()*100.0))

Accuracy: 77.216% (4.968%)


You can see that we report both the mean and the standard deviation of the performance
measure. When summarizing performance measures, it is a good practice to summarize the
distribution of the measures, in this case assuming a Gaussian distribution of performance (a
very reasonable assumption) and recording the mean and standard deviation.

### Leave One Out Cross Validation

You can configure cross validation so that the size of the fold is 1 ($k$ is set to the number of
observations in your dataset). This variation of cross validation is called leave-one-out cross
validation. The result is a large number of performance measures that can be summarized in an effort to give a more reasonable estimate of the accuracy of your model on unseen data.

A downside is that it can be a computationally more expensive procedure than k-fold cross
validation. In the example below we use leave-one-out cross validation.

In [ ]:
# Evaluate using Leave One Out Cross Validation
from pandas import read_csv
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
# load data
filename = '/content/sample_data/Corrosion_Detection_Ships.csv'
names = ['Years_since_last_inspection',
              'Water_salinity',
              'Water_pressure',
              'Coating_thickness',
              'Anti_corrosion_concentration',
              'Hull_material_density',
              'Inspection_history',
              'Ship_age',
              'Hull_Condition']
data = read_csv(filename, names=names)
array = data.values
X = array[:,0:8]
Y = array[:,8]
num_folds = 10
loocv = LeaveOneOut()
model = LogisticRegression(max_iter=500)
results = cross_val_score(model, X, Y, cv=loocv)
print("Accuracy: %.3f%% (%.3f%%)" % (results.mean()*100.0, results.std()*100.0))

Accuracy: 77.604% (41.689%)


You can see in the standard deviation that the score has more variance than the k-fold cross
validation results described above.

### Repeated Random Test-Train Splits

Another variation on $k$-fold cross validation is to create a random split of the data like the
train/test split described above, but repeat the process of splitting and evaluation of the
algorithm multiple times, like cross validation. This has the speed of using a train/test split and
the reduction in variance in the estimated performance of $k$-fold cross validation. You can also
repeat the process many more times as needed to improve the accuracy. A down side is that
repetitions may include much of the same data in the train or the test split from run to run,
introducing redundancy into the evaluation. The example below splits the data into a 67%/33%
train/test split and repeats the process 10 times.

In [ ]:
# Evaluate using Shuffle Split Cross Validation
from pandas import read_csv
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
# load data
filename = '/content/sample_data/Corrosion_Detection_Ships.csv'
names = ['Years_since_last_inspection',
              'Water_salinity',
              'Water_pressure',
              'Coating_thickness',
              'Anti_corrosion_concentration',
              'Hull_material_density',
              'Inspection_history',
              'Ship_age',
              'Hull_Condition']
data = read_csv(filename, names=names)
array = data.values
X = array[:,0:8]
Y = array[:,8]
n_splits = 10
test_size = 0.33
seed = 7
kfold = ShuffleSplit(n_splits=n_splits, test_size=test_size, random_state=seed)
model = LogisticRegression(max_iter=500)
results = cross_val_score(model, X, Y, cv=kfold)
# Applying the string formatting to the string itself.
print("Accuracy: %.3f%% (%.3f%%)" % (results.mean()*100.0, results.std()*100.0))

Accuracy: 76.535% (2.235%)


We can see that in this case the distribution of the performance measure is on par with
$k$-fold cross validation above.

### What Techniques to Use When
This section lists some tips to consider what resampling technique to use in different circum-
stances.
* Generally _k_-fold cross validation is the _gold standard_ for evaluating the performance of a
machine learning algorithm on unseen data with _k_ set to 3, 5, or 10.
* Using a train/test split is good for speed when using a slow algorithm and produces
performance estimates with lower bias when using large datasets.
* Techniques like leave-one-out cross validation and repeated random splits can be useful
intermediates when trying to balance variance in the estimated performance, model
training speed and dataset size.

The best advice is to experiment and find a technique for your problem that is fast and
produces reasonable estimates of performance that you can use to make decisions. If in doubt,
use 10-fold cross validation.